collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.5752688
color:
  saturation: 1
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#88B4BD'
    - '#F4C577'
    - '#BDBDA3'
    - '#5C995D'
  rhythmicContrast: 1
layout_spectrum: 1
name: Lets Multiverse
